output "import_manifest" {
    description = "KubeConfig file generated by Rancher for the imported K3s cluster"
    value = var.register_cluster ? rancher2_cluster.k3s_single_node_cluster[0].kube_config : ""
    sensitive = true
}

output "cluster_id" {
    description = "Cluster ID for the imported K3S cluster"
    value = var.register_cluster ? rancher2_cluster.k3s_single_node_cluster[0].id : ""
}